apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkride-shuma-f-cl-role
  namespace: checkride-shuma-f
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - triggerbindings
      - clusterinterceptors
    verbs:
      - get
      - list
      - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checkride-shuma-f-cl-rolebinding
  namespace: checkride-shuma-f
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    namespace: checkride-shuma-f
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checkride-shuma-f-cl-role