apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-deploy
spec:
  params:
    - name: app-namespace
      description: namespace that deployment will be tested in
    - name: app-name
      description: the name of the app
  workspaces:
    - name: source
      description: contains the cloned git repo
  results:
    - name: service-port
    - name: resource-type
  steps:
    - name: deploy
      image: docker.io/enzobarrett/kubectl:latest
      workingDir: $(workspaces.source.path)
      env:
        - name: VITE_API_BASE_URL
          value: https://checkride-shuma-b-checkride-shuma-b.apps.687717108a3a4d1edcbc3cee.ap1.techzone.ibm.com
      script: |
        #!/bin/sh
        cd k8s
        set -e
        APP_NAMESPACE="$(params.app-namespace)"

        echo -e "Deploying into: ${APP_NAMESPACE}"
        cat ./manifests.yaml
        kubectl apply -n ${APP_NAMESPACE} -f ./manifests.yaml --validate=false > results.out
        cat results.out
    - name: verify-deploy
      image: docker.io/enzobarrett/kubectl:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        cd k8s
        set -e
        APP_NAMESPACE="$(params.app-namespace)"
        APP_NAME="$(params.app-name)"

        cat results.out | \
          grep -E "deployment|statefulset|integrationserver|queuemanager" | \
          sed "s/deployment.apps/deployment/g" | \
          sed "s/statefulset.apps/statefulset/g" | \
          sed "s/configured//g" | \
          sed "s/created//g" | \
          sed "s/unchanged//g" | while read target; do
            echo "Waiting for rollout of ${target} in ${APP_NAMESPACE}"
            kubectl rollout status -n ${APP_NAMESPACE} ${target}
          done